### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by joseguzman1337**
update readme.md

### CODE REVIEW

**Review by walmsles — COMMENTED** [review]
Hi, thanks for fixing up my formatting in the documentation. I appreciate it.   May I ask why line 28 in the deployment steps is required ?

**Comment by joseguzman1337** [comment]
anytime at your service the reason is this= when i followed your instructions from master branch, the process itself reported that missing dependencies, regards.

**Review by walmsles — CHANGES_REQUESTED** [review]
Happy to merge in the formatting changes, but the instruction change needs to be removed.  This is specific to your linux env. setup and is not needed for most users in most environments.

**Comment by walmsles** [comment]
Closing as have applied the minor formatting changes

**Pull request closed without merging**
